name: Test Go API
on: 
  push:
    paths:
      - "*.go"
      - "internal/*"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - "*.go"
      - "internal/*"
      - "go.mod"
      - "go.sum"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Test altv
        run: go test
        working-directory: .
      - name: Test altv/events
        run: go test
        working-directory: ./events