name: Test changes
on: [push, pull_request]

jobs:
  test-windows:
    name: Test changes on Windows
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Create exmaple main.go
        shell: bash
        run: |
          cat <<EOF >main.go
          package main

          import "C"
          import "github.com/shockdev04/altv-go-pkg/alt"

          func main() { }

          //export onStart
          func onStart() {
          alt.LogInfo("Resource Started")
          }

          //export onStop
          func onStop() {
          alt.LogInfo("Resource Stopped")
          }

      - name: Build
        shell: cmd
        run: go build -o alt-test.dll -buildmode=c-shared

  test-linux:
    name: Test changes on Linux
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Create exmaple main.go
        shell: bash
        run: |
            cat <<EOF >main.go
            package main

            import "C"
            import "github.com/shockdev04/altv-go-pkg/alt"

            func main() { }

            //export onStart
            func onStart() {
            alt.LogInfo("Resource Started")
            }

            //export onStop
            func onStop() {
            alt.LogInfo("Resource Stopped")
            }

      - name: Build
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install gcc-8 g++-8
          export CGO_LDFLAGS="-g -02 -ldl"
          go build -o alt-test.so -buildmode=c-shared